// Package pac generates and serves a Proxy Auto-Config (PAC) file that
// mirrors the same direct-vs-proxy decision used for SSH, so a browser
// pointed at it gets the same "direct if local, SOCKS5 via jump host if
// not" behavior for each route's configured destinations.
package pac

import (
	"fmt"
	"net"
	"strconv"
	"strings"

	"ssh-autoproxy/internal/config"
)

// Generate renders the PAC JavaScript for the given routes. proxyNeeded
// maps route name to whether that route currently needs its jump host
// (true) or is reachable directly (false) — see netstate.Evaluate.
// Destinations outside every route's host_patterns/host_subnets, and any
// route with no SocksProxy configured, always return DIRECT — general
// browsing must never be routed through a personal tunnel, and a route
// without a SOCKS listener has nothing to proxy through.
//
// frontAddr, when non-empty, is the daemon's own front-door proxy
// listener (see internal/proxy): proxied hosts are sent there rather than
// to their route's own socks_proxy, and the listener picks the tunnel per
// connection. Empty keeps the original per-route addresses.
func Generate(routes []config.Route, proxyNeeded map[string]bool, frontAddr string) string {
	var b strings.Builder
	b.WriteString("// Generated by ssh-autoproxy — do not edit by hand.\n")
	b.WriteString("// Regenerated automatically whenever the network state changes.\n")
	b.WriteString("function FindProxyForURL(url, host) {\n")

	for _, route := range routes {
		if route.SocksProxy == nil {
			continue
		}
		proxyValue := "DIRECT"
		if proxyNeeded[route.Name] {
			addr := frontAddr
			if addr == "" {
				addr = net.JoinHostPort(route.SocksProxy.Bind, strconv.Itoa(route.SocksProxy.Port))
			}
			proxyValue = fmt.Sprintf("SOCKS5 %s; DIRECT", addr)
		}
		for _, pattern := range route.HostPatterns {
			fmt.Fprintf(&b, "    if (shExpMatch(host, %q)) {\n        return %q; // route: %s\n    }\n", pattern, proxyValue, route.Name)
		}
		for _, cidr := range route.HostSubnets {
			network, netmask, err := cidrToNetmask(cidr)
			if err != nil {
				continue
			}
			fmt.Fprintf(&b, "    if (isInNet(host, %q, %q)) {\n        return %q; // route: %s\n    }\n", network, netmask, proxyValue, route.Name)
		}
	}

	b.WriteString("    return \"DIRECT\";\n")
	b.WriteString("}\n")
	return b.String()
}

func cidrToNetmask(cidr string) (network, netmask string, err error) {
	_, ipnet, err := net.ParseCIDR(cidr)
	if err != nil {
		return "", "", err
	}
	return ipnet.IP.String(), net.IP(ipnet.Mask).String(), nil
}
